### ISSUE TITLE
Speed up tree-sitter-language update script

### ISSUE THREAD

**Issue by Luni-4** [mozilla/rust-code-analysis#367]
- [ ] Consider only the files associated to a `tree-sitter-language` when `rust-code-analyses` computes the metrics
- [ ] Compare metrics in parallel using the `multiprocess` package

**Comment by marco-c** [comment]
Using `async` would be nicer than `multiprocessing` and give you a similar level of parallelism (most of the time is likely spent in executing programs and reading files, so what you want to parallelize is waits rather than computation, and async achieves that). `multiprocessing` in Python is pretty painful.

**Comment by Luni-4** [comment]
> Using `async` would be nicer than `multiprocessing` and give you a similar level of parallelism (most of the time is likely spent in executing programs and reading files, so what you want to parallelize is waits rather than computation, and async achieves that). `multiprocessing` in Python is pretty painful.

True, I haven't thought about `async`, thank you! :)
