### ISSUE TITLE
Does this tool actually work?

### ISSUE THREAD

**Issue by STashakkori** [mozilla/rust-code-analysis#643]
Downloaded and installed the tool. Running the CLI doesn't seem to do anything. Also seeing no documentation on how to use this so the only guide is the usage. Is this intended to work or is it still in development? Thank you

**Comment by marco-c** [comment]
@STashakkori I'm not sure how you missed the docs, there is a "Documentation" link in the Usage section of the README :P

**Comment by waynr** [comment]
@marco-c I read the docs before trying to run the command and here are the problems I ran into with the docs:

* there is no top-level "this is how to run the CLI" landing page
* the CLI seems to require options to do anything at all, which is pretty counter-intuitive; the more intuitive thing to do would be to instead of requiring optional flags for the CLI to do anything at all (eg `-m` to generate metrics), require subcommands, eg `rust-code-analysis-cli [SUBCOMMAND]` where `[SUBCOMMAND]` could be one of `metrics`, `nodes`, or `rest-api`
* even once i finally found the documentation page that indicated the need to use `-m`, there are still more optional flags required for the program to do anything at all which suggests to me one of two possible improvements:
  * for each `[SUBCOMMAND]` include sensible defaults for the required flags; for the `metrics` subcommand default `-O` to `json` (or whatever) and `-o` to `rust-code-analysis-metrics`
  * if you don't want defaults, another user-friendly option would be to have the program exit with a sensible error message

As it is, without this just running `rust-code-analysis-cli` with none of the required optional arguments causes the program to mysteriously terminate with a 0 exit code.

**Comment by marco-c** [comment]
@waynr please file separate issues for your suggestions to improve the docs or the CLI.
